<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Smile\DebugToolbar\ViewModel\Loader;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Loader $viewModel */
$viewModel = $block->getData('viewModel');
?>

<?php if ($viewModel->isToolbarEnabled()): ?>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        fetch('<?= $escaper->escapeUrl($block->getUrl('smile_debug_toolbar')) ?>', {
            method: 'GET',
        }).then((response) => {
            return response.text();
        }).then((html) => {
            const fragment = document.createRange().createContextualFragment(html);
            document.body.append( fragment);
        }).catch((error) => {
            console.log(`Failed to load the debug toolbar: ${error}`);
        });
    });
</script>
<?php endif ?>
