<?php

use Magento\Framework\Cache\Backend\Redis;
use Smile\DebugToolbar\Block\Zone\Cache;

/** @var Cache $block */
$list = $block->getCacheUsage();

foreach ($list as $key => $row) {
    $row['identifier'] = $block->formatValue($row['identifier'], [], 'text');
    $row['call_count'] = $block->formatValue($row['call_count'], [], 'number');
    $row['total_size'] = $block->formatValue($row['total_size'], [], 'size_ko');
    $row['mean_size'] = $block->formatValue($row['mean_size'], ['gt' => 250 * 1024], 'size_ko');
    $row['total_time'] = $block->formatValue($row['total_time'], [], 'time_ms');
    $row['mean_time'] = $block->formatValue($row['mean_time'], ['gt' => 0.01], 'time_ms');
    $row['html_info'] = $block->buildHtmlInfo($row['calls']);
    $list[$key] = $row;
}
?>

<?= /* @noEscape */ $block->displayTable(
    'Cache Usage',
    $list,
    [
        'identifier' => ['label' => 'Identifier', 'width' => ''],
        'call_count' => ['label' => 'Calls', 'width' => '100px'],
        'total_size' => ['label' => 'Total Size', 'width' => '120px'],
        'mean_size' => ['label' => 'Mean Size', 'width' => '120px'],
        'total_time' => ['label' => 'Total Time', 'width' => '120px'],
        'mean_time' => ['label' => 'Mean Time',    'width' => '120px'],
    ],
    'html_info'
) ?>

<?php
$sections = $block->getStatsPerAction();

$sections['Number'] = [
    'total' => $block->formatValue($sections['Count']['total'], [], 'number'),
    'load' => $block->formatValue($sections['Count']['load'], [], 'number'),
    'save' => $block->formatValue($sections['Count']['save'], [], 'number'),
    'remove' => $block->formatValue($sections['Count']['remove'], [], 'number'),
];

$sections['Size'] = [
    'total' => $block->formatValue($sections['Size']['total'], [], 'size'),
    'load' => $block->formatValue($sections['Size']['load'], [], 'size'),
    'save' => $block->formatValue($sections['Size']['save'], [], 'size'),
    'remove' => $block->formatValue($sections['Size']['remove'], [], 'size'),
];

$sections['Time'] = [
    'total' => $block->formatValue($sections['Time']['total'], ['gt' => 0.5], 'time'),
    'load' => $block->formatValue($sections['Time']['load'], ['gt' => 0.5], 'time'),
    'save' => $block->formatValue($sections['Time']['save'], ['gt' => 0.5], 'time'),
    'remove' => $block->formatValue($sections['Time']['remove'], ['gt' => 0.5], 'time'),
];

$block->addToSummary('Cache', 'Count', $sections['Count']['total'])
    ->addToSummary('Cache', 'Time', $sections['Time']['total'])
    ->addToSummary('Cache', 'Size', $sections['Size']['total']);
?>

<?= /* @noEscape */ $block->displaySectionsGrouped($sections) ?>

<?php
$sections = [
    'Types' => $block->getCacheTypes(),
    'Config' => [
        'Backend' => $block->formatValue($block->getCacheBackend(), ['neq' => Redis::class], 'text'),
        'Config' => $block->getCacheInfo(),
    ],
];

foreach ($sections['Types'] as $type => $value) {
    $sections['Types'][$type] = $block->formatValue($value, ['neq' => 'Enabled'], 'text');
}
?>

<?= /* @noEscape */ $block->displaySections($sections) ?>
