<?php

use Magento\Framework\Escaper;
use Smile\DebugToolbar\Block\Zone\Database;

/** @var Database $block */
/** @var Escaper $escaper */
try {
    $queries = $block->getQueries();
    $list = [];
} catch (Exception $e) {
    echo '<h2>PROFILER ERROR</h2>';
    echo $escaper->escapeHtml($e->getMessage());
    return;
}

foreach ($queries as $key => $query) {
    $list[$key] = [
        'type' => $block->formatValue($query->getTypeAsString(), [], 'center'),
        'time' => $block->formatValue($query->getElapsedSecs(), ['gt' => 0.05], 'time_ms'),
        'query' => $block->formatValue($query->getQuery(), [], 'code_sql'),
        'html_info' => $block->buildHtmlInfo($query->getQueryParams(), $query->getTrace()),
    ];
}
?>

<?= /* @noEscape */ $block->displayTable(
    'MySQL Queries',
    $list,
    [
        'type' => ['label' => 'Type', 'width' => '100px'],
        'time' => ['label' => 'Time', 'width' => '100px'],
        'query' => ['label' => 'Query', 'width' => ''],
    ],
    'html_info'
) ?>

<?php
$sections = [
    'Count' => $block->getCountPerTypes(),
    'Time' => $block->getTimePerTypes(),
];

$sections['Time'] = [
    'total' => $block->formatValue($sections['Time']['total'], ['gt' => 1.], 'time'),
    'select' => $block->formatValue($sections['Time']['select'], ['gt' => 1.], 'time'),
    'insert' => $block->formatValue($sections['Time']['insert'], ['gt' => 0.5], 'time'),
    'update' => $block->formatValue($sections['Time']['update'], ['gt' => 0.5], 'time'),
    'delete' => $block->formatValue($sections['Time']['delete'], ['gt' => 0.5], 'time'),
    'query' => $block->formatValue($sections['Time']['query'], ['gt' => 0.5], 'time'),
    'transaction' => $block->formatValue($sections['Time']['transaction'], ['gt' => 0.5], 'time'),
    'connect' => $block->formatValue($sections['Time']['connect'], ['gt' => 0.01], 'time'),
];

$sections['Number'] = [
    'total' => $block->formatValue($sections['Count']['total'], ['gt' => 250], 'number'),
    'select' => $block->formatValue($sections['Count']['select'], ['gt' => 250], 'number'),
    'insert' => $block->formatValue($sections['Count']['insert'], ['gt' => 15], 'number'),
    'update' => $block->formatValue($sections['Count']['update'], ['gt' => 15], 'number'),
    'delete' => $block->formatValue($sections['Count']['delete'], ['gt' => 15], 'number'),
    'query' => $block->formatValue($sections['Count']['query'], ['gt' => 15], 'number'),
    'transaction' => $block->formatValue($sections['Count']['transaction'], ['gt' => 15], 'number'),
    'connect' => $block->formatValue($sections['Count']['connect'], ['gt' => 1], 'number'),
];

$block->addToSummary('Mysql', 'Queries', $sections['Count']['total'])
    ->addToSummary('Mysql', 'Time', $sections['Time']['total']);
?>

<?= /* @noEscape */ $block->displaySectionsGrouped($sections) ?>

<?php
$sections = [
    'Server' => [
        'Version' => $block->getMysqlVersion(),
    ],
];
?>

<?= /* @noEscape */ $block->displaySections($sections) ?>
