<?php

use Smile\DebugToolbar\Block\Zone\Layout;

/** @var Layout $block */
$sections = [
    'Handles' => $block->getHandles()
];
?>

<?= /* @noEscape */ $block->displaySections($sections) ?>
<table class="st-profiler">
    <colgroup>
        <col style="width: 40%" />
        <col style="width: 60%" />
    </colgroup>
    <thead>
        <tr>
            <th>Name</th>
            <td>Info</td>
        </tr>
    </thead>
    <tbody>
        <?= /* @noEscape */ $block->displayLayoutTable() ?>
    </tbody>
</table>
