<?php

use Smile\DebugToolbar\Block\Zone\Observer;

/** @var Observer $block */
$stats = $block->getObserverStats();

$sections = [
    'Used Events' => [
        'Count' => 0,
        'Called' => 0,
        'Time' => 0,
    ],
    'Unused Events' => [
        'Count' => 0,
        'Called' => 0,
        'Time' => 0,
    ],
];

$used = [];
$unused = [];
foreach ($stats as $event) {
    $section = &$sections['Unused Events'];
    $list = &$unused;
    if ($event['nb_observers'] > 0) {
        $section = &$sections['Used Events'];
        $list = &$used;
        $event['html_info'] = $block->buildHtmlInfo($event['observers']);
    }

    $section['Count']++;
    $section['Called'] += $event['nb_call'];
    $section['Time'] += $event['time_total'];

    $event['event_name'] = $block->formatValue($event['event_name'], [], 'text');
    $event['nb_call'] = $block->formatValue($event['nb_call'], [], 'number');
    $event['time_total'] = $block->formatValue($event['time_total'], ['gt' => 0.5], 'time_ms');
    $event['time_mean'] = $block->formatValue($event['time_mean'], ['gt' => 0.5], 'time_ms');
    $event['nb_observers'] = $block->formatValue($event['nb_observers'], ['gt' => 20], 'number');

    $list[] = $event;
}
unset($stats);
?>

<?= /* @noEscape */ $block->displayTable(
    'Used Events',
    $used,
    [
        'event_name' => ['label' => 'Name', 'width' => ''],
        'nb_call' => ['label' => 'Calls', 'width' => '100px'],
        'time_total' => ['label' => 'Total Time', 'width' => '120px'],
        'time_mean' => ['label' => 'Mean Time', 'width' => '120px'],
        'nb_observers' => ['label' => 'Observers', 'width' => '130px'],
    ],
    'html_info'
) ?>

<?= /* @noEscape */ $block->displayTable(
    'Unused Events',
    $unused,
    [
        'event_name' => ['label' => 'Name', 'width' => ''],
        'nb_call' => ['label' => 'Calls', 'width' => '100px'],
        'time_total' => ['label' => 'Total Time', 'width' => '120px'],
        'time_mean' => ['label' => 'Mean Time', 'width' => '120px'],
    ]
)?>

<?php
$sections = [
    'Used Events' => [
        'Count' => $block->formatValue($sections['Used Events']['Count'], ['gt' => 100], 'number'),
        'Called' => $block->formatValue($sections['Used Events']['Called'], ['gt' => 1000], 'number'),
        'Time' => $block->formatValue($sections['Used Events']['Time'], ['gt' => 1.000], 'time'),
    ],
    'Unused Events' => [
        'Count' => $block->formatValue($sections['Unused Events']['Count'], [], 'number'),
        'Called' => $block->formatValue($sections['Unused Events']['Called'], [], 'number'),
        'Time' => $block->formatValue($sections['Unused Events']['Time'], ['gt' => 0.5], 'time'),
    ],
];

$block->addToSummary('Observers', 'Used Events', $sections['Used Events']['Count'])
    ->addToSummary('Observers', 'Called Events', $sections['Used Events']['Called'])
    ->addToSummary('Observers', 'Time', $sections['Used Events']['Time']);
?>

<?= /* @noEscape */ $block->displaySectionsGrouped($sections) ?>
