<?php

use Smile\DebugToolbar\Block\Zone\Preference;

/** @var Preference $block */
$list = $block->getPreferenceStats();
$preferences = [];
foreach ($list as $abstraction => $implementation) {
    $preferences[] = [
        'abstraction' => $block->formatValue($abstraction, [], 'text'),
        'implementation' => $block->formatValue($implementation, [], 'text'),
    ];
}
unset($list);
?>

<?= /* @noEscape */ $block->displayTable(
    'Preferences',
    $preferences,
    [
        'abstraction' => ['label' => 'Abstraction', 'width' => ''],
        'implementation' => ['label' => 'Implementation', 'width' => ''],
    ]
) ?>

<?php
$decoratedClasses = [];
$plugins = $block->getPluginStats();
foreach ($plugins as $key => $row) {
    $decoratedClasses[$row['original_classname']] = true;

    $row['classname'] = $block->formatValue($row['classname'], [], 'text');
    $row['name'] = $block->formatValue($row['name'], [], 'text');
    $row['method_count'] = $block->formatValue($row['method_count'], ['gt' => 10], 'center');
    $row['original_classname'] = $block->formatValue($row['original_classname'], [], 'text');
    $row['html_info'] = $block->buildPluginHtmlInfo($row['methods']);

    $plugins[$key] = $row;
}
?>

<?= /* @noEscape */ $block->displayTable(
    'Plugins',
    $plugins,
    [
        'classname' => ['label' => 'Plugin Class', 'width' => ''],
        'name' => ['label' => 'Plugin Name', 'width' => ''],
        'method_count' => ['label' => 'Methods', 'width' => '100px'],
        'original_classname' => ['label' => 'Subject', 'width' => ''],
    ],
    'html_info'
)?>

<?php
$sections = [
    'Declared Plugins' => [
        'Plugins' => $block->formatValue(count($plugins), [], 'number'),
        'Classes observed by plugin(s)' => $block->formatValue(count($decoratedClasses), [], 'number'),
    ],
    'Preferences' => [
        'Preferences' => $block->formatValue(count($preferences), [], 'number'),
    ],
];

$block->addToSummary('Preferences', 'Preferences', $sections['Preferences']['Preferences'])
    ->addToSummary('Preferences', 'Plugins', $sections['Declared Plugins']['Plugins'])
    ->addToSummary(
        'Preferences',
        'Classes observed by plugin(s)',
        $sections['Declared Plugins']['Classes observed by plugin(s)']
    );
?>

<?= /* @noEscape */ $block->displaySections($sections) ?>
