<?php

use Smile\DebugToolbar\Block\Zone\Request;

/** @var Request $block */
$request = $block->getRequest();

$sections = [
    'HTTP' => [
        'Version' => $request->getVersion(),
        'Scheme' => $request->getScheme(),
        'Method' => $request->getMethod(),
        'IP' => $request->getClientIp(),
        'URL' => $request->getUriString(),
    ],
    'Action' => [
        'Path' => $request->getPathInfo() ?: '/',
        'Full Action' => $request->getFullActionName(),
        'Module' => $request->getModuleName(),
        'Group' => $request->getControllerName(),
        'Action' => $request->getActionName(),
    ],
    'Route' => [
        'Module' => $request->getControllerModule(),
        'Route Name' => $request->getRouteName(),
        'Front Name' => $request->getFrontName(),
        'Controller' => $block->getControllerClassName(),
    ],
    'User Params' => (array) $request->getUserParams(),
    'Get' => (array) $request->getQuery(),
    'Post' => (array) $request->getPost(),
    'Files' => (array) $request->getFiles(),
    'Env' => array_merge((array) $request->getEnv(), (array) $request->getServer()),
    'Headers' => [],
    // phpcs:ignore
    'Cookies' => $_COOKIE,
];

foreach ($request->getHeaders() as $header) {
    $sections['Headers'][$header->getFieldName()] = $header->getFieldValue();
}

$sections['Headers']['Cookie'] = 'See in Cookies section';

$block->addToSummary('Request', 'Path', $sections['Action']['Path'])
    ->addToSummary('Request', 'Method', $sections['HTTP']['Method'])
    ->addToSummary('Request', 'Full Action', $sections['Action']['Full Action']);
?>

<?= /* @noEscape */ $block->displaySections($sections) ?>
