<?php

use Smile\DebugToolbar\Block\Zone\Response;

/** @var Response $block */
$response = $block->getResponse();

$length = mb_strlen((string) $response->getContent());

$headers = [];
foreach ($response->getHeaders() as $header) {
    $headers[$header->getFieldName()] = $header->getFieldValue();
}

$tags = [];
if (array_key_exists('X-Magento-Tags', $headers)) {
    $tags = explode(',', $headers['X-Magento-Tags']);
    $headers['X-Magento-Tags'] = 'see in Full Page Cache section';
    sort($tags);
}

$esi = $block->getEsiUrlList();

$sections = [
    'HTTP' => [
        'Version' => $block->formatValue($response->getVersion(), [], 'text'),
        'Cookie' => $response->getCookie(),
        'Response Code' => $block->formatValue($response->getHttpResponseCode(), ['gt' => 399], 'text'),
        'Reason Phrase' => $response->getReasonPhrase(),
        'Status Code' => $block->formatValue($response->getStatusCode(), ['gt' => 399], 'text'),
    ],
    'Headers' => $headers,
    'Response' => [
        'Date' => date('Y-m-d H:i:s'),
        'Size' => $block->formatValue($length, ['gt' => 512 * 1024], 'size'),
    ],
    'Full Page Cache' => [
        'Mode' => $block->formatValue($block->getFullPageCacheMode(), ['neq' => 'varnish'], 'text'),
        'Tags' => $tags,
        'ESI' => $esi,
    ],
];

$block->addToSummary('Response', 'Date', $sections['Response']['Date']);
$block->addToSummary('Response', 'Size', $sections['Response']['Size']);
$block->addToSummary('Full Page Cache', 'FPC Mode', $sections['Full Page Cache']['Mode']);
$block->addToSummary('Full Page Cache', 'FPC Tags', count($tags));
$block->addToSummary('Full Page Cache', 'ESI Tags', count($esi));
?>

<?= /* @noEscape */ $block->displaySections($sections) ?>
